/**
 * Mock data for Supply Chain Map - Arizona Beverages
 * Used when VITE_SUPPLY_CHAIN_USE_MOCK=true
 */

// Arizona Beverages Trucks
export const mockTrucks = [
  {
    truck_id: 'AZ-TRK-001',
    status: 'in-transit',
    latitude: 40.7128,
    longitude: -74.0060,
    destination_id: 'AZ-DC-WOODBURY',
    destination_name: 'Woodbury, NY DC',
    speed: 55,
    fuel_level: 78,
    cargo_capacity: 1200,
    cargo_loaded: 1050,
  },
  {
    truck_id: 'AZ-TRK-002',
    status: 'delayed',
    latitude: 36.1627,
    longitude: -86.7816,
    destination_id: 'AZ-DC-LAVERGNE',
    destination_name: 'La Vergne, TN DC',
    speed: 0,
    fuel_level: 45,
    cargo_capacity: 1200,
    cargo_loaded: 920,
  },
  {
    truck_id: 'AZ-TRK-003',
    status: 'in-transit',
    latitude: 39.9612,
    longitude: -82.9988,
    destination_id: 'AZ-DC-COLUMBUS',
    destination_name: 'Columbus, OH DC',
    speed: 62,
    fuel_level: 82,
    cargo_capacity: 1000,
    cargo_loaded: 850,
  },
  {
    truck_id: 'AZ-TRK-004',
    status: 'delivered',
    latitude: 40.8176,
    longitude: -73.4668,
    destination_id: 'AZ-DC-WOODBURY',
    destination_name: 'Woodbury, NY DC',
    speed: 0,
    fuel_level: 35,
    cargo_capacity: 1200,
    cargo_loaded: 0,
  },
  {
    truck_id: 'AZ-TRK-005',
    status: 'in-transit',
    latitude: 35.2271,
    longitude: -80.8431,
    destination_id: 'AZ-STR-CHARLOTTE',
    destination_name: 'Charlotte Retailer',
    speed: 58,
    fuel_level: 65,
    cargo_capacity: 800,
    cargo_loaded: 720,
  },
  {
    truck_id: 'AZ-TRK-006',
    status: 'idle',
    latitude: 36.0159,
    longitude: -86.5819,
    destination_id: null,
    destination_name: null,
    speed: 0,
    fuel_level: 90,
    cargo_capacity: 1200,
    cargo_loaded: 0,
  },
  {
    truck_id: 'AZ-TRK-007',
    status: 'in-transit',
    latitude: 41.4993,
    longitude: -81.6944,
    destination_id: 'AZ-STR-CLEVELAND',
    destination_name: 'Cleveland Metro Store',
    speed: 48,
    fuel_level: 55,
    cargo_capacity: 800,
    cargo_loaded: 680,
  },
  {
    truck_id: 'AZ-TRK-008',
    status: 'maintenance',
    latitude: 39.9612,
    longitude: -82.9988,
    destination_id: null,
    destination_name: null,
    speed: 0,
    fuel_level: 70,
    cargo_capacity: 1000,
    cargo_loaded: 0,
  },
];

// Arizona Beverages Distribution Centers and Stores
export const mockStores = [
  // Distribution Centers
  {
    store_id: 'AZ-DC-WOODBURY',
    name: 'Woodbury, NY DC',
    latitude: 40.8176,
    longitude: -73.4668,
    facility_type: 'distribution-center',
    stock_level: 85,
    capacity: 50000,
    current_stock: 42500,
    demand_rate: 1200,
    available_stock: 40000,
    committed_stock: 2500,
    reorder_point: 15000,
    safety_stock: 10000,
    region: 'Northeast',
    total_skus: 45,
    sku_details: [
      { sku_id: 'AZ-GT-23OZ', product_name: 'Green Tea 23oz', current_qty: 15000, stock_status: 'in-stock', trend: 'stable' },
      { sku_id: 'AZ-AP-20OZ', product_name: 'Arnold Palmer 20oz', current_qty: 12000, stock_status: 'in-stock', trend: 'increasing' },
      { sku_id: 'AZ-FP-128OZ', product_name: 'Fruit Punch Gallon', current_qty: 5000, stock_status: 'low-stock', trend: 'decreasing' },
    ],
  },
  {
    store_id: 'AZ-DC-LAVERGNE',
    name: 'La Vergne, TN DC',
    latitude: 36.0159,
    longitude: -86.5819,
    facility_type: 'distribution-center',
    stock_level: 72,
    capacity: 40000,
    current_stock: 28800,
    demand_rate: 950,
    available_stock: 26000,
    committed_stock: 2800,
    reorder_point: 12000,
    safety_stock: 8000,
    region: 'Southeast',
    total_skus: 42,
    sku_details: [
      { sku_id: 'AZ-GT-23OZ', product_name: 'Green Tea 23oz', current_qty: 10000, stock_status: 'in-stock', trend: 'stable' },
      { sku_id: 'AZ-MG-15.5OZ', product_name: 'Mucho Mango 15.5oz', current_qty: 8000, stock_status: 'in-stock', trend: 'increasing' },
    ],
  },
  {
    store_id: 'AZ-DC-COLUMBUS',
    name: 'Columbus, OH DC',
    latitude: 39.9612,
    longitude: -82.9988,
    facility_type: 'distribution-center',
    stock_level: 45,
    capacity: 35000,
    current_stock: 15750,
    demand_rate: 800,
    available_stock: 13500,
    committed_stock: 2250,
    reorder_point: 10000,
    safety_stock: 7000,
    region: 'Midwest',
    total_skus: 38,
    sku_details: [
      { sku_id: 'AZ-RX-16OZ', product_name: 'RX Energy 16oz', current_qty: 3000, stock_status: 'low-stock', trend: 'decreasing' },
      { sku_id: 'AZ-AP-20OZ', product_name: 'Arnold Palmer 20oz', current_qty: 5000, stock_status: 'in-stock', trend: 'stable' },
    ],
  },
  // Retail Stores
  {
    store_id: 'AZ-STR-NYC',
    name: 'NYC Metro Store',
    latitude: 40.7580,
    longitude: -73.9855,
    facility_type: 'store',
    stock_level: 65,
    capacity: 5000,
    current_stock: 3250,
    demand_rate: 180,
    region: 'Northeast',
    total_skus: 25,
  },
  {
    store_id: 'AZ-STR-CHARLOTTE',
    name: 'Charlotte Retailer',
    latitude: 35.2271,
    longitude: -80.8431,
    facility_type: 'store',
    stock_level: 28,
    capacity: 4000,
    current_stock: 1120,
    demand_rate: 150,
    region: 'Southeast',
    total_skus: 22,
  },
  {
    store_id: 'AZ-STR-CLEVELAND',
    name: 'Cleveland Metro Store',
    latitude: 41.4993,
    longitude: -81.6944,
    facility_type: 'store',
    stock_level: 55,
    capacity: 3500,
    current_stock: 1925,
    demand_rate: 120,
    region: 'Midwest',
    total_skus: 20,
  },
  {
    store_id: 'AZ-STR-PHILLY',
    name: 'Philadelphia Store',
    latitude: 39.9526,
    longitude: -75.1652,
    facility_type: 'store',
    stock_level: 78,
    capacity: 4500,
    current_stock: 3510,
    demand_rate: 160,
    region: 'Northeast',
    total_skus: 24,
  },
  {
    store_id: 'AZ-STR-NASHVILLE',
    name: 'Nashville Store',
    latitude: 36.1627,
    longitude: -86.7816,
    facility_type: 'store',
    stock_level: 42,
    capacity: 3000,
    current_stock: 1260,
    demand_rate: 110,
    region: 'Southeast',
    total_skus: 18,
  },
];

// Alerts
export const mockAlerts = [
  {
    id: 1,
    alert_type: 'inventory-alert',
    agent_id: 'inventory-manager',
    title: 'Low Stock Alert - Columbus DC',
    message: 'RX Energy 16oz below reorder point at Columbus, OH DC. Current: 3,000 cases, Reorder Point: 5,000 cases',
    latitude: 39.9612,
    longitude: -82.9988,
    status: 'active',
    priority: 9,
    severity: 'critical',
    suggested_actions: ['Transfer 2,000 cases from La Vergne DC', 'Expedite supplier order', 'Notify sales team'],
  },
  {
    id: 2,
    alert_type: 'route-alert',
    agent_id: 'route-optimizer',
    title: 'Traffic Delay - I-40 Corridor',
    message: 'AZ-TRK-002 experiencing delays on I-40 near Nashville. ETA +2.5 hours',
    latitude: 36.1627,
    longitude: -86.7816,
    status: 'active',
    priority: 7,
    severity: 'high',
    suggested_actions: ['Reroute via I-24', 'Notify La Vergne DC of delay', 'Update customer ETAs'],
    alternate_route: [
      [36.1627, -86.7816],
      [36.0, -86.0],
      [35.8, -85.5],
      [36.0159, -86.5819],
    ],
  },
  {
    id: 3,
    alert_type: 'inventory-alert',
    agent_id: 'inventory-manager',
    title: 'Critical Stock - Charlotte Store',
    message: 'Charlotte Retailer at 28% stock level. Risk of stockout within 2 days',
    latitude: 35.2271,
    longitude: -80.8431,
    status: 'active',
    priority: 8,
    severity: 'high',
    suggested_actions: ['Dispatch emergency shipment from La Vergne DC', 'Prioritize AZ-TRK-005 delivery'],
  },
  {
    id: 4,
    alert_type: 'maintenance-alert',
    agent_id: 'route-optimizer',
    title: 'Truck Maintenance Required',
    message: 'AZ-TRK-008 scheduled maintenance overdue by 3 days. Currently at Columbus, OH DC',
    latitude: 39.9612,
    longitude: -82.9988,
    status: 'active',
    priority: 6,
    severity: 'medium',
    suggested_actions: ['Schedule maintenance within 24 hours', 'Assign backup truck for pending routes'],
  },
  {
    id: 5,
    alert_type: 'demand-alert',
    agent_id: 'demand-forecaster',
    title: 'Demand Spike Predicted',
    message: 'Arnold Palmer 20oz demand expected to increase 35% in Northeast region due to heat wave forecast',
    latitude: 40.8176,
    longitude: -73.4668,
    status: 'active',
    priority: 7,
    severity: 'high',
    suggested_actions: ['Increase Woodbury DC stock by 5,000 cases', 'Coordinate with co-packers for expedited production'],
  },
  {
    id: 6,
    alert_type: 'weather-alert',
    agent_id: 'demand-forecaster',
    title: 'Weather Impact Warning',
    message: 'Severe thunderstorms forecast for Tennessee region. May affect La Vergne DC operations and outbound shipments',
    latitude: 36.0159,
    longitude: -86.5819,
    status: 'active',
    priority: 5,
    severity: 'medium',
    suggested_actions: ['Pre-position inventory at regional stores', 'Delay non-critical shipments'],
  },
];

// AI Agents
export const mockAgents = [
  {
    id: 'route-optimizer',
    name: 'Ruute.AI',
    icon: '🚛',
    type: 'route-optimizer',
    color: '#3b82f6',
    status: 'scanning',
    activity: 'Optimizing 8 active routes',
    quick_questions: ['Show delayed trucks', 'Find alternate routes', 'Calculate fuel savings'],
    metrics_tracked: ['On-time delivery rate', 'Fuel efficiency', 'Route optimization'],
  },
  {
    id: 'inventory-manager',
    name: 'Stox.AI',
    icon: '📦',
    type: 'inventory-manager',
    color: '#8b5cf6',
    status: 'alert',
    activity: '2 critical stock alerts',
    quick_questions: ['Check stock levels', 'Predict stockouts', 'Recommend transfers'],
    metrics_tracked: ['Stock levels', 'Turnover rate', 'Reorder points'],
  },
  {
    id: 'demand-forecaster',
    name: 'Markets.AI',
    icon: '🌍',
    type: 'demand-forecaster',
    color: '#06b6d4',
    status: 'scanning',
    activity: 'Analyzing weather patterns',
    quick_questions: ['Forecast next week', 'Weather impacts', 'Seasonal trends'],
    metrics_tracked: ['Demand forecasts', 'Weather correlation', 'Event impacts'],
    forecast_horizon: 14,
    accuracy_rate: 87,
  },
  {
    id: 'cost-optimizer',
    name: 'Cost.AI',
    icon: '💰',
    type: 'cost-optimizer',
    color: '#10b981',
    status: 'idle',
    activity: 'Monitoring cost metrics',
    quick_questions: ['Find cost savings', 'Consolidation opportunities', 'ROI analysis'],
    metrics_tracked: ['Cost per mile', 'Warehouse utilization', 'Carrier rates'],
  },
];

// AI Actions for the command center
export const mockAIActions = [
  {
    id: 'action-001',
    timestamp: new Date(Date.now() - 5 * 60000),
    agent_id: 'inventory-manager',
    agent_name: 'Stox.AI',
    action_type: 'transfer',
    description: 'Transfer 2,000 cases RX Energy from La Vergne to Columbus DC',
    predicted_impact: 15,
    confidence: 92,
    status: 'pending-approval',
    requires_approval: true,
    auto_approved: false,
    facility_affected: 'AZ-DC-COLUMBUS',
    cost_saved: 3200,
    time_saved: 48,
  },
  {
    id: 'action-002',
    timestamp: new Date(Date.now() - 12 * 60000),
    agent_id: 'route-optimizer',
    agent_name: 'Ruute.AI',
    action_type: 'route',
    description: 'Reroute AZ-TRK-002 via I-24 to avoid I-40 congestion',
    predicted_impact: 8,
    confidence: 88,
    status: 'completed',
    requires_approval: false,
    auto_approved: true,
    facility_affected: 'AZ-DC-LAVERGNE',
    cost_saved: 450,
    time_saved: 2.5,
  },
  {
    id: 'action-003',
    timestamp: new Date(Date.now() - 20 * 60000),
    agent_id: 'demand-forecaster',
    agent_name: 'Markets.AI',
    action_type: 'order',
    description: 'Increase Arnold Palmer 20oz production order by 5,000 cases',
    predicted_impact: 12,
    confidence: 85,
    status: 'pending-approval',
    requires_approval: true,
    auto_approved: false,
    facility_affected: 'AZ-DC-WOODBURY',
    cost_saved: 8500,
    time_saved: 72,
  },
  {
    id: 'action-004',
    timestamp: new Date(Date.now() - 35 * 60000),
    agent_id: 'cost-optimizer',
    agent_name: 'Cost.AI',
    action_type: 'optimization',
    description: 'Consolidate AZ-TRK-005 and AZ-TRK-007 deliveries',
    predicted_impact: 10,
    confidence: 94,
    status: 'completed',
    requires_approval: false,
    auto_approved: true,
    facility_affected: null,
    cost_saved: 1200,
    time_saved: 4,
  },
];

// Autopilot Status
export const mockAutopilotStatus = {
  mode: 'proposals-ready',
  pending_count: 2,
  actions_today: 12,
  cost_saved_week: 28500,
  issues_prevented: 7,
  ai_confidence_avg: 89,
};

// Truck routes for visualization
export const mockRoutes = {
  'AZ-TRK-001': [
    [40.0, -75.0],
    [40.3, -74.5],
    [40.5, -74.0],
    [40.7128, -74.0060],
    [40.8176, -73.4668],
  ],
  'AZ-TRK-002': [
    [35.5, -88.0],
    [35.8, -87.5],
    [36.0, -87.0],
    [36.1627, -86.7816],
    [36.0159, -86.5819],
  ],
  'AZ-TRK-003': [
    [39.5, -84.0],
    [39.7, -83.5],
    [39.9612, -82.9988],
  ],
  'AZ-TRK-005': [
    [34.5, -82.0],
    [34.8, -81.5],
    [35.0, -81.0],
    [35.2271, -80.8431],
  ],
  'AZ-TRK-007': [
    [40.5, -82.5],
    [40.8, -82.2],
    [41.0, -82.0],
    [41.4993, -81.6944],
  ],
};
