/**
 * Mock data for Supply Chain Map - Arizona Beverages
 * Used when VITE_SUPPLY_CHAIN_USE_MOCK=true
 * Spread across the entire United States
 */

// Arizona Beverages Trucks - Spread across US
export const mockTrucks = [
  {
    truck_id: 'AZ-TRK-001',
    status: 'in-transit',
    latitude: 34.0522,
    longitude: -118.2437,
    destination_id: 'AZ-DC-PHOENIX',
    destination_name: 'Phoenix, AZ DC',
    speed: 62,
    fuel_level: 78,
    cargo_capacity: 1200,
    cargo_loaded: 1050,
  },
  {
    truck_id: 'AZ-TRK-002',
    status: 'delayed',
    latitude: 29.7604,
    longitude: -95.3698,
    destination_id: 'AZ-DC-DALLAS',
    destination_name: 'Dallas, TX DC',
    speed: 0,
    fuel_level: 45,
    cargo_capacity: 1200,
    cargo_loaded: 920,
  },
  {
    truck_id: 'AZ-TRK-003',
    status: 'in-transit',
    latitude: 41.8781,
    longitude: -87.6298,
    destination_id: 'AZ-DC-CHICAGO',
    destination_name: 'Chicago, IL DC',
    speed: 58,
    fuel_level: 82,
    cargo_capacity: 1000,
    cargo_loaded: 850,
  },
  {
    truck_id: 'AZ-TRK-004',
    status: 'delivered',
    latitude: 47.6062,
    longitude: -122.3321,
    destination_id: 'AZ-DC-SEATTLE',
    destination_name: 'Seattle, WA DC',
    speed: 0,
    fuel_level: 35,
    cargo_capacity: 1200,
    cargo_loaded: 0,
  },
  {
    truck_id: 'AZ-TRK-005',
    status: 'in-transit',
    latitude: 25.7617,
    longitude: -80.1918,
    destination_id: 'AZ-STR-MIAMI',
    destination_name: 'Miami Retailer',
    speed: 55,
    fuel_level: 65,
    cargo_capacity: 800,
    cargo_loaded: 720,
  },
  {
    truck_id: 'AZ-TRK-006',
    status: 'idle',
    latitude: 39.7392,
    longitude: -104.9903,
    destination_id: null,
    destination_name: null,
    speed: 0,
    fuel_level: 90,
    cargo_capacity: 1200,
    cargo_loaded: 0,
  },
  {
    truck_id: 'AZ-TRK-007',
    status: 'in-transit',
    latitude: 40.7128,
    longitude: -74.0060,
    destination_id: 'AZ-STR-NYC',
    destination_name: 'NYC Metro Store',
    speed: 48,
    fuel_level: 55,
    cargo_capacity: 800,
    cargo_loaded: 680,
  },
  {
    truck_id: 'AZ-TRK-008',
    status: 'maintenance',
    latitude: 33.4484,
    longitude: -112.0740,
    destination_id: null,
    destination_name: null,
    speed: 0,
    fuel_level: 70,
    cargo_capacity: 1000,
    cargo_loaded: 0,
  },
  {
    truck_id: 'AZ-TRK-009',
    status: 'in-transit',
    latitude: 37.7749,
    longitude: -122.4194,
    destination_id: 'AZ-DC-LOSANGELES',
    destination_name: 'Los Angeles, CA DC',
    speed: 60,
    fuel_level: 72,
    cargo_capacity: 1200,
    cargo_loaded: 1100,
  },
  {
    truck_id: 'AZ-TRK-010',
    status: 'in-transit',
    latitude: 32.7767,
    longitude: -96.7970,
    destination_id: 'AZ-STR-HOUSTON',
    destination_name: 'Houston Store',
    speed: 65,
    fuel_level: 80,
    cargo_capacity: 1000,
    cargo_loaded: 900,
  },
];

// Arizona Beverages Distribution Centers and Stores - Spread across US
export const mockStores = [
  // Distribution Centers - Major hubs across US
  {
    store_id: 'AZ-DC-PHOENIX',
    name: 'Phoenix, AZ DC',
    latitude: 33.4484,
    longitude: -112.0740,
    facility_type: 'distribution-center',
    stock_level: 85,
    capacity: 60000,
    current_stock: 51000,
    demand_rate: 1400,
    available_stock: 48000,
    committed_stock: 3000,
    reorder_point: 18000,
    safety_stock: 12000,
    region: 'Southwest',
    total_skus: 50,
    sku_details: [
      { sku_id: 'AZ-GT-23OZ', product_name: 'Green Tea 23oz', current_qty: 18000, stock_status: 'in-stock', trend: 'stable' },
      { sku_id: 'AZ-AP-20OZ', product_name: 'Arnold Palmer 20oz', current_qty: 15000, stock_status: 'in-stock', trend: 'increasing' },
      { sku_id: 'AZ-FP-128OZ', product_name: 'Fruit Punch Gallon', current_qty: 8000, stock_status: 'in-stock', trend: 'stable' },
    ],
  },
  {
    store_id: 'AZ-DC-LOSANGELES',
    name: 'Los Angeles, CA DC',
    latitude: 34.0522,
    longitude: -118.2437,
    facility_type: 'distribution-center',
    stock_level: 72,
    capacity: 55000,
    current_stock: 39600,
    demand_rate: 1600,
    available_stock: 36000,
    committed_stock: 3600,
    reorder_point: 16000,
    safety_stock: 11000,
    region: 'West Coast',
    total_skus: 48,
    sku_details: [
      { sku_id: 'AZ-GT-23OZ', product_name: 'Green Tea 23oz', current_qty: 14000, stock_status: 'in-stock', trend: 'increasing' },
      { sku_id: 'AZ-MG-15.5OZ', product_name: 'Mucho Mango 15.5oz', current_qty: 10000, stock_status: 'in-stock', trend: 'increasing' },
    ],
  },
  {
    store_id: 'AZ-DC-CHICAGO',
    name: 'Chicago, IL DC',
    latitude: 41.8781,
    longitude: -87.6298,
    facility_type: 'distribution-center',
    stock_level: 42,
    capacity: 45000,
    current_stock: 18900,
    demand_rate: 1200,
    available_stock: 16500,
    committed_stock: 2400,
    reorder_point: 13000,
    safety_stock: 9000,
    region: 'Midwest',
    total_skus: 42,
    sku_details: [
      { sku_id: 'AZ-RX-16OZ', product_name: 'RX Energy 16oz', current_qty: 3500, stock_status: 'low-stock', trend: 'decreasing' },
      { sku_id: 'AZ-AP-20OZ', product_name: 'Arnold Palmer 20oz', current_qty: 6000, stock_status: 'in-stock', trend: 'stable' },
    ],
  },
  {
    store_id: 'AZ-DC-DALLAS',
    name: 'Dallas, TX DC',
    latitude: 32.7767,
    longitude: -96.7970,
    facility_type: 'distribution-center',
    stock_level: 68,
    capacity: 50000,
    current_stock: 34000,
    demand_rate: 1100,
    available_stock: 31000,
    committed_stock: 3000,
    reorder_point: 15000,
    safety_stock: 10000,
    region: 'South Central',
    total_skus: 45,
    sku_details: [
      { sku_id: 'AZ-GT-23OZ', product_name: 'Green Tea 23oz', current_qty: 12000, stock_status: 'in-stock', trend: 'stable' },
      { sku_id: 'AZ-LM-23OZ', product_name: 'Lemon Tea 23oz', current_qty: 9000, stock_status: 'in-stock', trend: 'stable' },
    ],
  },
  {
    store_id: 'AZ-DC-SEATTLE',
    name: 'Seattle, WA DC',
    latitude: 47.6062,
    longitude: -122.3321,
    facility_type: 'distribution-center',
    stock_level: 78,
    capacity: 35000,
    current_stock: 27300,
    demand_rate: 800,
    available_stock: 25000,
    committed_stock: 2300,
    reorder_point: 10000,
    safety_stock: 7000,
    region: 'Pacific Northwest',
    total_skus: 38,
    sku_details: [
      { sku_id: 'AZ-GT-23OZ', product_name: 'Green Tea 23oz', current_qty: 10000, stock_status: 'in-stock', trend: 'stable' },
      { sku_id: 'AZ-AP-20OZ', product_name: 'Arnold Palmer 20oz', current_qty: 8000, stock_status: 'in-stock', trend: 'stable' },
    ],
  },
  {
    store_id: 'AZ-DC-ATLANTA',
    name: 'Atlanta, GA DC',
    latitude: 33.7490,
    longitude: -84.3880,
    facility_type: 'distribution-center',
    stock_level: 55,
    capacity: 40000,
    current_stock: 22000,
    demand_rate: 950,
    available_stock: 20000,
    committed_stock: 2000,
    reorder_point: 12000,
    safety_stock: 8000,
    region: 'Southeast',
    total_skus: 40,
    sku_details: [
      { sku_id: 'AZ-GT-23OZ', product_name: 'Green Tea 23oz', current_qty: 8000, stock_status: 'in-stock', trend: 'stable' },
      { sku_id: 'AZ-FP-128OZ', product_name: 'Fruit Punch Gallon', current_qty: 4000, stock_status: 'low-stock', trend: 'decreasing' },
    ],
  },
  // Retail Stores - Spread across US
  {
    store_id: 'AZ-STR-NYC',
    name: 'NYC Metro Store',
    latitude: 40.7128,
    longitude: -74.0060,
    facility_type: 'store',
    stock_level: 65,
    capacity: 5000,
    current_stock: 3250,
    demand_rate: 200,
    region: 'Northeast',
    total_skus: 25,
  },
  {
    store_id: 'AZ-STR-MIAMI',
    name: 'Miami Beach Store',
    latitude: 25.7617,
    longitude: -80.1918,
    facility_type: 'store',
    stock_level: 28,
    capacity: 4000,
    current_stock: 1120,
    demand_rate: 180,
    region: 'Southeast',
    total_skus: 22,
  },
  {
    store_id: 'AZ-STR-DENVER',
    name: 'Denver Metro Store',
    latitude: 39.7392,
    longitude: -104.9903,
    facility_type: 'store',
    stock_level: 58,
    capacity: 3500,
    current_stock: 2030,
    demand_rate: 130,
    region: 'Mountain',
    total_skus: 20,
  },
  {
    store_id: 'AZ-STR-SANFRAN',
    name: 'San Francisco Store',
    latitude: 37.7749,
    longitude: -122.4194,
    facility_type: 'store',
    stock_level: 75,
    capacity: 4500,
    current_stock: 3375,
    demand_rate: 170,
    region: 'West Coast',
    total_skus: 24,
  },
  {
    store_id: 'AZ-STR-HOUSTON',
    name: 'Houston Store',
    latitude: 29.7604,
    longitude: -95.3698,
    facility_type: 'store',
    stock_level: 48,
    capacity: 4000,
    current_stock: 1920,
    demand_rate: 160,
    region: 'South Central',
    total_skus: 23,
  },
  {
    store_id: 'AZ-STR-BOSTON',
    name: 'Boston Store',
    latitude: 42.3601,
    longitude: -71.0589,
    facility_type: 'store',
    stock_level: 82,
    capacity: 3500,
    current_stock: 2870,
    demand_rate: 140,
    region: 'Northeast',
    total_skus: 21,
  },
  {
    store_id: 'AZ-STR-PORTLAND',
    name: 'Portland Store',
    latitude: 45.5152,
    longitude: -122.6784,
    facility_type: 'store',
    stock_level: 70,
    capacity: 3000,
    current_stock: 2100,
    demand_rate: 110,
    region: 'Pacific Northwest',
    total_skus: 19,
  },
  {
    store_id: 'AZ-STR-MINNEAPOLIS',
    name: 'Minneapolis Store',
    latitude: 44.9778,
    longitude: -93.2650,
    facility_type: 'store',
    stock_level: 38,
    capacity: 3200,
    current_stock: 1216,
    demand_rate: 120,
    region: 'Midwest',
    total_skus: 18,
  },
  {
    store_id: 'AZ-STR-LASVEGAS',
    name: 'Las Vegas Store',
    latitude: 36.1699,
    longitude: -115.1398,
    facility_type: 'store',
    stock_level: 62,
    capacity: 4000,
    current_stock: 2480,
    demand_rate: 190,
    region: 'Southwest',
    total_skus: 24,
  },
  {
    store_id: 'AZ-STR-NEWOLREANS',
    name: 'New Orleans Store',
    latitude: 29.9511,
    longitude: -90.0715,
    facility_type: 'store',
    stock_level: 45,
    capacity: 3000,
    current_stock: 1350,
    demand_rate: 125,
    region: 'Gulf Coast',
    total_skus: 20,
  },
];

// Alerts - Spread across US
export const mockAlerts = [
  {
    id: 1,
    alert_type: 'inventory-alert',
    agent_id: 'inventory-manager',
    title: 'Low Stock Alert - Chicago DC',
    message: 'RX Energy 16oz below reorder point at Chicago, IL DC. Current: 3,500 cases, Reorder Point: 5,000 cases',
    latitude: 41.8781,
    longitude: -87.6298,
    status: 'active',
    priority: 9,
    severity: 'critical',
    suggested_actions: ['Transfer 2,500 cases from Dallas DC', 'Expedite supplier order', 'Notify sales team'],
  },
  {
    id: 2,
    alert_type: 'route-alert',
    agent_id: 'route-optimizer',
    title: 'Traffic Delay - I-10 Houston',
    message: 'AZ-TRK-002 experiencing delays on I-10 near Houston. ETA +3 hours',
    latitude: 29.7604,
    longitude: -95.3698,
    status: 'active',
    priority: 7,
    severity: 'high',
    suggested_actions: ['Reroute via US-290', 'Notify Dallas DC of delay', 'Update customer ETAs'],
    alternate_route: [
      [29.7604, -95.3698],
      [30.2, -95.8],
      [31.0, -96.2],
      [32.7767, -96.7970],
    ],
  },
  {
    id: 3,
    alert_type: 'inventory-alert',
    agent_id: 'inventory-manager',
    title: 'Critical Stock - Miami Store',
    message: 'Miami Beach Store at 28% stock level. Risk of stockout within 2 days',
    latitude: 25.7617,
    longitude: -80.1918,
    status: 'active',
    priority: 8,
    severity: 'high',
    suggested_actions: ['Dispatch emergency shipment from Atlanta DC', 'Prioritize AZ-TRK-005 delivery'],
  },
  {
    id: 4,
    alert_type: 'maintenance-alert',
    agent_id: 'route-optimizer',
    title: 'Truck Maintenance Required',
    message: 'AZ-TRK-008 scheduled maintenance overdue by 3 days. Currently at Phoenix, AZ DC',
    latitude: 33.4484,
    longitude: -112.0740,
    status: 'active',
    priority: 6,
    severity: 'medium',
    suggested_actions: ['Schedule maintenance within 24 hours', 'Assign backup truck for pending routes'],
  },
  {
    id: 5,
    alert_type: 'demand-alert',
    agent_id: 'demand-forecaster',
    title: 'Demand Spike Predicted - West Coast',
    message: 'Arnold Palmer 20oz demand expected to increase 40% in California due to heat wave forecast',
    latitude: 34.0522,
    longitude: -118.2437,
    status: 'active',
    priority: 7,
    severity: 'high',
    suggested_actions: ['Increase Los Angeles DC stock by 8,000 cases', 'Coordinate with co-packers for expedited production'],
  },
  {
    id: 6,
    alert_type: 'weather-alert',
    agent_id: 'demand-forecaster',
    title: 'Hurricane Warning - Gulf Coast',
    message: 'Tropical storm approaching Gulf Coast. May affect Houston and New Orleans operations',
    latitude: 29.9511,
    longitude: -90.0715,
    status: 'active',
    priority: 8,
    severity: 'high',
    suggested_actions: ['Pre-position inventory at inland locations', 'Delay non-critical shipments', 'Activate emergency protocols'],
  },
  {
    id: 7,
    alert_type: 'inventory-alert',
    agent_id: 'inventory-manager',
    title: 'Low Stock - Minneapolis Store',
    message: 'Minneapolis Store at 38% stock level approaching critical threshold',
    latitude: 44.9778,
    longitude: -93.2650,
    status: 'active',
    priority: 6,
    severity: 'medium',
    suggested_actions: ['Schedule replenishment from Chicago DC', 'Monitor demand patterns'],
  },
];

// AI Agents
export const mockAgents = [
  {
    id: 'route-optimizer',
    name: 'Route.AI',
    icon: '🚛',
    type: 'route-optimizer',
    color: '#3b82f6',
    status: 'scanning',
    activity: 'Optimizing 10 active routes',
    quick_questions: ['Show delayed trucks', 'Find alternate routes', 'Calculate fuel savings'],
    metrics_tracked: ['On-time delivery rate', 'Fuel efficiency', 'Route optimization'],
  },
  {
    id: 'inventory-manager',
    name: 'Stox.AI',
    icon: '📦',
    type: 'inventory-manager',
    color: '#0078d4',
    status: 'alert',
    activity: '3 critical stock alerts',
    quick_questions: ['Check stock levels', 'Predict stockouts', 'Recommend transfers'],
    metrics_tracked: ['Stock levels', 'Turnover rate', 'Reorder points'],
  },
  {
    id: 'demand-forecaster',
    name: 'Markets.AI',
    icon: '🌍',
    type: 'demand-forecaster',
    color: '#06b6d4',
    status: 'scanning',
    activity: 'Analyzing weather patterns',
    quick_questions: ['Forecast next week', 'Weather impacts', 'Seasonal trends'],
    metrics_tracked: ['Demand forecasts', 'Weather correlation', 'Event impacts'],
    forecast_horizon: 14,
    accuracy_rate: 87,
  },
  {
    id: 'cost-optimizer',
    name: 'Cost.AI',
    icon: '💰',
    type: 'cost-optimizer',
    color: '#10b981',
    status: 'idle',
    activity: 'Monitoring cost metrics',
    quick_questions: ['Find cost savings', 'Consolidation opportunities', 'ROI analysis'],
    metrics_tracked: ['Cost per mile', 'Warehouse utilization', 'Carrier rates'],
  },
];

// AI Actions for the command center
export const mockAIActions = [
  {
    id: 'action-001',
    timestamp: new Date(Date.now() - 5 * 60000),
    agent_id: 'inventory-manager',
    agent_name: 'Stox.AI',
    action_type: 'transfer',
    description: 'Transfer 2,500 cases RX Energy from Dallas to Chicago DC',
    predicted_impact: 15,
    confidence: 92,
    status: 'pending-approval',
    requires_approval: true,
    auto_approved: false,
    facility_affected: 'AZ-DC-CHICAGO',
    cost_saved: 3800,
    time_saved: 48,
  },
  {
    id: 'action-002',
    timestamp: new Date(Date.now() - 12 * 60000),
    agent_id: 'route-optimizer',
    agent_name: 'Route.AI',
    action_type: 'route',
    description: 'Reroute AZ-TRK-002 via US-290 to avoid I-10 congestion',
    predicted_impact: 8,
    confidence: 88,
    status: 'completed',
    requires_approval: false,
    auto_approved: true,
    facility_affected: 'AZ-DC-DALLAS',
    cost_saved: 520,
    time_saved: 3,
  },
  {
    id: 'action-003',
    timestamp: new Date(Date.now() - 20 * 60000),
    agent_id: 'demand-forecaster',
    agent_name: 'Markets.AI',
    action_type: 'order',
    description: 'Increase Arnold Palmer 20oz production order by 8,000 cases for West Coast',
    predicted_impact: 12,
    confidence: 85,
    status: 'pending-approval',
    requires_approval: true,
    auto_approved: false,
    facility_affected: 'AZ-DC-LOSANGELES',
    cost_saved: 12500,
    time_saved: 72,
  },
  {
    id: 'action-004',
    timestamp: new Date(Date.now() - 35 * 60000),
    agent_id: 'cost-optimizer',
    agent_name: 'Cost.AI',
    action_type: 'optimization',
    description: 'Consolidate Seattle and Portland deliveries via AZ-TRK-004',
    predicted_impact: 10,
    confidence: 94,
    status: 'completed',
    requires_approval: false,
    auto_approved: true,
    facility_affected: null,
    cost_saved: 1800,
    time_saved: 5,
  },
];

// Autopilot Status
export const mockAutopilotStatus = {
  mode: 'proposals-ready',
  pending_count: 2,
  actions_today: 15,
  cost_saved_week: 42500,
  issues_prevented: 9,
  ai_confidence_avg: 89,
};

// Truck routes for visualization - Routes from truck's current position to destination
// Each route starts at the truck's current lat/lng and ends at the destination facility
export const mockRoutes = {
  // AZ-TRK-001: LA area (34.0522, -118.2437) -> Phoenix DC (33.4484, -112.0740)
  'AZ-TRK-001': [
    [34.0522, -118.2437],  // Truck current position (LA)
    [33.9, -116.5],        // Waypoint
    [33.6, -114.5],        // Waypoint
    [33.4484, -112.0740],  // Destination: Phoenix DC
  ],
  // AZ-TRK-002: Houston (29.7604, -95.3698) -> Dallas DC (32.7767, -96.7970) - DELAYED
  'AZ-TRK-002': [
    [29.7604, -95.3698],   // Truck current position (Houston)
    [30.8, -96.2],         // Waypoint
    [31.8, -96.5],         // Waypoint
    [32.7767, -96.7970],   // Destination: Dallas DC
  ],
  // AZ-TRK-003: Chicago area (41.8781, -87.6298) -> Chicago DC (same location - arriving)
  'AZ-TRK-003': [
    [41.8781, -87.6298],   // Truck at Chicago DC (arrived)
  ],
  // AZ-TRK-005: Miami area (25.7617, -80.1918) -> Miami Store (same - delivering)
  'AZ-TRK-005': [
    [25.7617, -80.1918],   // Truck at Miami (arrived)
  ],
  // AZ-TRK-007: NYC (40.7128, -74.0060) -> NYC Store (same - delivering)
  'AZ-TRK-007': [
    [40.7128, -74.0060],   // Truck at NYC (arrived)
  ],
  // AZ-TRK-009: SF (37.7749, -122.4194) -> LA DC (34.0522, -118.2437)
  'AZ-TRK-009': [
    [37.7749, -122.4194],  // Truck current position (SF)
    [36.5, -121.0],        // Waypoint
    [35.3, -119.5],        // Waypoint
    [34.0522, -118.2437],  // Destination: LA DC
  ],
  // AZ-TRK-010: Dallas (32.7767, -96.7970) -> Houston Store (29.7604, -95.3698)
  'AZ-TRK-010': [
    [32.7767, -96.7970],   // Truck current position (Dallas)
    [31.5, -96.0],         // Waypoint
    [30.5, -95.6],         // Waypoint
    [29.7604, -95.3698],   // Destination: Houston Store
  ],
};
